### ISSUE TITLE
backgroundColor returns warning for having a capital letter in strict mode

### ISSUE THREAD

**Issue by Kyle772** [NWylynko/react-simple-badges#2]
Warning: React does not recognize the `backgroundColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `backgroundcolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in img (created by Badge)
    in Badge (at Landing.js:52)
    in div (at Landing.js:51)
    in div (at Landing.js:47)
    in div (at Landing.js:45)
    in label (at Landing.js:44)
    in section (at Landing.js:42)
    in LandingPage (at App.js:49)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:49)
    in Switch (at App.js:46)
    in div (at App.js:44)
    in App (created by Context.Consumer)
    in withRouter(App) (at src/index.js:11)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:11)
    in StrictMode (at src/index.js:10)

**Comment by NWylynko** [comment]
Yup this occurs because its just passing the props straight through to the img element. It needs to remove the custom props like backgroundColor, logoColor, name and label. Ill get it fixed asap.
